### ISSUE TITLE
How is this code different from language-docker?

### ISSUE THREAD

**Issue by peti** [beijaflor-io/haskell-language-dockerfile#12]
I am very confused and hope that you can help me out understanding what the actual difference between language-docker and language-dockerfile is? The former project appears to be more actively maintained? Is there are reasoning I can follow to decide whether I want to base my own coding efforts on or the other version of this library?

**Comment by lorenzo** [comment]
@peti It was me who extracted language-docker out of this repo, modernised it, and brought it up to date with all newer Dockerfile changes. I'm actively maintaining it

**Comment by peti** [comment]
@lorenzo, I see! Thank you very much for the explanation.

It might be a good idea to mention the origin of `language-docker` in its Cabal description or in the README, maybe, to make it more obvious to users looking at both packages to see which one is the newer one.
